apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: postgres-sec
type: Opaque
data:  
  password: sdfvsnfsfsss243  # Replace with actual password encoded in base64
  username: admin # Replace with actual username encoded in base64
